apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-dev
  labels:
    app: user-service
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      env: dev
  template:
    metadata:
      labels:
        app: user-service
        env: dev
    spec:
      containers:
        - name: user-service
          image: 728301184457.dkr.ecr.us-east-2.amazonaws.com/draff1800/sample-repository:dev
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: user-service-config-dev
            - secretRef:
                name: user-service-secret-dev
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
