apiVersion: v1
kind: Service
metadata:
  name: user-service-dev
  labels:
    app: user-service
    env: dev
spec:
  selector:
    app: user-service
    env: dev
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
