name: Deploy to EKS

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-2 --name sample-cluster-2

      - name: Deploy to dev namespace
        run: |
          kubectl apply -f k8s/dev/ --namespace=dev

      - name: Deploy to prod namespace
        if: github.event_name == 'release'
        run: |
          kubectl apply -f k8s/prod/ --namespace=prod
