name: Deploy to EKS (Prod)

on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Deploy to AWS EKS (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-2 --name sample-cluster

      - name: Deploy to Prod Namespace
        run: |
          kubectl apply -f k8s/prod/ --namespace=prod